### ISSUE TITLE
Pydantic v2 incompatibility

### ISSUE THREAD

**Issue by LeoColomb** [lowatt/lowatt-grdf#19]
The latest Pydantic release, v2, brings some breaking changes.
As this module is a non-pinned dependencies, incompatibility issues are raised.

> If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with `@model_validator`.

This is indeed documented on Pydantic's migration guide: https://docs.pydantic.dev/latest/migration/#validator-and-root_validator-are-deprecated

This specific directive is used here: https://github.com/search?q=repo%3Alowatt%2Flowatt-grdf+root_validator&type=code

I note that there is a migration tool that could help fix this in a rather simply way: https://docs.pydantic.dev/latest/migration/#code-transformation-tool

**Comment by philpep** [comment]
Hi, thanks for reporting.

We could switch to pydantic v2, but there's no backward compatibility with pydantic v1 :/

I think we could use https://github.com/python-attrs/cattrs or plain dataclasses instead.

**Comment by LeoColomb** [comment]
As you wish 🙂
My two cents would be to start pinning dependencies (via a [pipfile](https://pipenv.pypa.io/en/latest/pipfile/) or even a raw `requirements.txt`)
